Repository Soviet-Linux/OUR, pull requests merged in 2023-11, with the labels that each got.

#7 Added an example for an ecmp file
  example.ecmp
  readme.md
Labels: size/M

#6 reworking the repo
  all.db
  base/src/attr.ecmp
  base/src/bash.ecmp
  base/src/curl.ecmp
  base/src/git.ecmp
  base/src/grub.ecmp
  base/src/intltool.ecmp
  base/src/mandoc.ecmp
  base/src/openssh.ecmp
  base/src/openssl.ecmp
  base/src/popt.ecmp
  base/src/sqlite.ecmp
  base/src/zlib.ecmp
  testing/src/bzip2.ecmp
  testing/src/efibootmgr.ecmp
  testing/src/efivar.ecmp
  testing/src/freetype.ecmp
  testing/src/grub.ecmp
  testing/src/openssl.ecmp
  testing/src/perl.ecmp
  testing/src/readline.ecmp
Labels: size/L

#8 Fixed Nano
  all.db
  base/src/nano.ecmp
  testing/src/nano.ecmp
Labels: size/M

#10 Made Autorebuild of db CI
  .github/workflows/autorebuilddb.yml
Labels: size/S

#11 Made the readme better
  readme.md
Labels: size/M

#9 continued work on OUR
  all.db
  base/src/alsa-lib.ecmp
  base/src/apr.ecmp
  base/src/nano.ecmp
  community/readme.md
  community/src/bfc.ecmp
  extra/readme.md
  testing/src/apr-util.ecmp
  testing/src/dependency-free/FLTK.ecmp
  testing/src/dependency-free/bzip2.ecmp
  testing/src/dependency-free/dash.ecmp
  testing/src/dependency-free/expat.ecmp
  testing/src/dependency-free/fftw.ecmp
  testing/src/dependency-free/fuse.ecmp
  testing/src/dependency-free/icu.ecmp
  testing/src/dependency-free/inih.ecmp
  testing/src/dependency-free/jansson.ecmp
  testing/src/dependency-free/libarchive.ecmp
  testing/src/dependency-free/libexif.ecmp
  testing/src/dependency-free/libffi.ecmp
  testing/src/dependency-free/libpng.ecmp
  testing/src/dependency-free/libtirpc.ecmp
  testing/src/dependency-free/libxml2.ecmp
  testing/src/dependency-free/lua.ecmp
  testing/src/dependency-free/lzo.ecmp
  testing/src/dependency-free/nasm.ecmp
  testing/src/dependency-free/neovim-bin.ecmp
  testing/src/dependency-free/nettle.ecmp
  testing/src/dependency-free/pcre.ecmp
  testing/src/dependency-free/perl-xml-parser.ecmp
  testing/src/dependency-free/perl.ecmp
  testing/src/dependency-free/php.ecmp
  testing/src/dependency-free/ruby.ecmp
  testing/src/dependency-free/sgml-common.ecmp
  testing/src/dependency-free/soshell.ecmp
  testing/src/dependency-free/sudo.ecmp
  testing/src/dependency-free/unzip.ecmp
  testing/src/dependency-free/w3m.ecmp
  testing/src/dependency-free/which.ecmp
  testing/src/dependency-free/xz.ecmp
Labels: size/M

#12 Continuing work on OUR
  all.db
  base/src/bzip2.ecmp
  base/src/dash.ecmp
  base/src/expat.ecmp
  base/src/fftw.ecmp
  base/src/fuse.ecmp
  base/src/icu.ecmp
  base/src/jansson.ecmp
  base/src/libarchive.ecmp
  base/src/libexif.ecmp
  base/src/libffi.ecmp
  base/src/libpng.ecmp
  base/src/libtirpc.ecmp
  base/src/libxml2.ecmp
  base/src/lua.ecmp
  community/src/FLTK.ecmp
  example.ecmp
  testing/src/dependency-free/FLTK.ecmp
  testing/src/dependency-free/lua.ecmp
  testing/src/dependency-met/lzo.ecmp
  testing/src/dependency-met/nasm.ecmp
  testing/src/dependency-met/neovim-bin.ecmp
  testing/src/dependency-met/nettle.ecmp
  testing/src/dependency-met/pcre.ecmp
  testing/src/dependency-met/perl-xml-parser.ecmp
  testing/src/dependency-met/perl.ecmp
  testing/src/dependency-met/php.ecmp
  testing/src/dependency-met/ruby.ecmp
  testing/src/dependency-met/sgml-common.ecmp
  testing/src/dependency-met/soshell.ecmp
  testing/src/dependency-met/sudo.ecmp
  testing/src/dependency-met/unzip.ecmp
  testing/src/dependency-met/w3m.ecmp
  testing/src/dependency-met/which.ecmp
  testing/src/dependency-met/xz.ecmp
  testing/src/flatpak.ecmp
  testing/src/inih.ecmp
Labels: size/L
