Repository Soviet-Linux/OUR, pull requests merged in 2024-07, with the labels that each got.

#133 updated example file
  example.ecmp
Labels: size/M

#134 updated the example
  example.ecmp
Labels: size/S

#136 new CI + cleanup
  .github/workflows/autorebuilddb.yml
  .github/workflows/build-db.yaml
  .github/workflows/check-pkg.yml
  .github/workflows/ourcustomci.yml
  .gitlab-ci.yml
  all.db
  build.sh
  cccp-test
  generated.txt
  mkall
Labels: size/L
