Repository Soviet-Linux/OUR, pull requests merged in 2024-05, with the labels that each got.

#111 coreutils
  base/src/coreutils.ecmp
Labels: size/M

#110 zstd
  base/src/zstd.ecmp
Labels: size/S

#109 tar
  base/src/tar.ecmp
Labels: size/S

#108 P11 kit
  base/src/p11-kit.ecmp
Labels: size/S

#107 libpipeline
  base/src/libpipeline.ecmp
Labels: size/S

#115 Coreutils
  base/patch/coreutils-9.5-i18n-1.patch
  base/src/coreutils.ecmp
Labels: size/XXL

#120 tzdb - time zone database
  base/src/tzdb.ecmp
Labels: size/S

#119 inetutils
  base/src/inetutils.ecmp
Labels: size/M

#125 gcc
  base/src/gcc.ecmp
Labels: size/M

#121 lzip
  base/src/lzip.ecmp
Labels: size/S

#106 Update man-db.ecmp
  base/src/man-db.ecmp
Labels: size/S

#113 Texinfo
  base/src/texinfo.ecmp
Labels: size/S

#116 shadow
  base/src/shadow.ecmp
Labels: size/M

#117 setuptools
  base/src/setuptools.ecmp
Labels: size/S

#126 systemd
  base/patch/systemd-255-upstream_fixes-1.patch
  base/src/systemd.ecmp
Labels: size/L

#128 Util linux
  base/src/util-linux.ecmp
Labels: size/M

#127 Python
  base/src/python.ecmp
Labels: size/S

#123 Dbus
  base/src/dbus.ecmp
Labels: size/M

#122 dbus-broker
  base/src/dbus-broker.ecmp
Labels: size/S

#114 make-ca
  base/src/make-ca.ecmp
Labels: size/S

#101 Added ninja
  base/src/ninja.ecmp
Labels: size/S

#103 Added psmisc
  base/src/psmisc.ecmp
Labels: size/S

#104 added procps-ng
  base/src/procps-ng.ecmp
Labels: size/S
