Repository Soviet-Linux/OUR, pull requests merged in 2024-01, with the labels that each got.

#19 Add cccp-test script
  cccp-test
Labels: size/XS

#27 acl
  base/src/acl.ecmp
Labels: size/S

#21 Added bison
  base/src/bison.ecmp
Labels: size/S

#20 Added automake
  base/src/autoconf.ecmp
  base/src/automake.ecmp
  cccp-test
Labels: size/M

#24 Fixed zlib
  base/src/zlib.ecmp
Labels: size/S

#28 attr
  base/src/attr.ecmp
Labels: size/S

#29 autoconf
  base/src/autoconf.ecmp
Labels: size/XS

#30 bash
  base/src/bash.ecmp
Labels: size/S

#31 bzip2
  base/src/bzip2.ecmp
Labels: size/S

#32 cmake
  base/src/cmake.ecmp
Labels: size/S

#33 Added libtool
  base/src/libtool.ecmp
Labels: size/S

#34 curl
  base/src/curl.ecmp
Labels: size/S

#22 Added file
  base/src/file.ecmp
Labels: size/S

#23 Added make
  base/src/make.ecmp
Labels: size/S

#35 expat
  base/src/expat.ecmp
Labels: size/S

#36 git
  base/src/git.ecmp
Labels: size/S

#40 libspm
  base/src/libspm.ecmp
Labels: size/XS

#39 libffi
  base/src/libffi.ecmp
Labels: size/S

#38 Libarchive
  base/src/libarchive.ecmp
Labels: size/S

#37 intltool
  base/src/intltool.ecmp
Labels: size/XS

#42 lzo
  base/src/lzo.ecmp
Labels: size/S

#43 m4
  base/src/m4.ecmp
Labels: size/XS

#44 xml-parser
  base/src/perl-xml-parser.ecmp
Labels: size/M

#45 updated git
  base/src/git.ecmp
Labels: size/XS

#46 nano
  base/src/nano.ecmp
Labels: size/S

#47 openssl
  base/src/openssl.ecmp
Labels: size/S

#48 perl
  base/src/perl.ecmp
Labels: size/S

#49 sqlite
  base/src/sqlite.ecmp
Labels: size/S

#50 sudo
  base/src/sudo.ecmp
Labels: size/S

#51 vim
  base/src/vim.ecmp
Labels: size/S
