Repository Soviet-Linux/OUR, pull requests merged in 2024-10, with the labels that each got.

#144 fix neovim
  extra/src/neovim.ecmp
Labels: size/XS

#148 fixes for python, remove unneeded code
  base/src/zlib.ecmp
Labels: size/XS

#147 pip and performance
  base/src/python.ecmp
Labels: size/XS

#150 CCCP/libSPM
  base/src/cccp.ecmp
  base/src/libspm.ecmp
Labels: size/M

#131 Neofetch
  extra/src/neofetch.ecmp
Labels: size/S

#141 Hyfetch
  extra/src/hyfetch.ecmp
Labels: size/S

#139 Wayland
  extra/src/graphics/cairo.ecmp
  extra/src/graphics/fontconfig.ecmp
  extra/src/graphics/freetype.ecmp
  extra/src/graphics/fribidi.ecmp
  extra/src/graphics/glslang.ecmp
  extra/src/graphics/harfbuzz.ecmp
  extra/src/graphics/libXau.ecmp
  extra/src/graphics/libdrm.ecmp
  extra/src/graphics/libjpeg-turbo.ecmp
  extra/src/graphics/libpng.ecmp
  extra/src/graphics/libxcb.ecmp
  extra/src/graphics/mesa.ecmp
  extra/src/graphics/pango.ecmp
  extra/src/graphics/pixman.ecmp
  extra/src/graphics/seatd.ecmp
  extra/src/graphics/util-macros.ecmp
  extra/src/graphics/xcb-proto.ecmp
  extra/src/graphics/xkeyboard-config.ecmp
  extra/src/graphics/xorg-build-env.ecmp
  extra/src/graphics/xorg-libs.ecmp
  extra/src/graphics/xorgproto.ecmp
  extra/src/lib/glib.ecmp
  extra/src/lib/gobject-introspection.ecmp
  extra/src/lib/libclc.ecmp
  extra/src/lib/libdisplay-info.ecmp
  extra/src/lib/libedit.ecmp
  extra/src/lib/libevdev.ecmp
  extra/src/lib/libinput.ecmp
  extra/src/lib/libxkbcommon.ecmp
  extra/src/lib/libxslt.ecmp
  extra/src/lib/mtdev.ecmp
  extra/src/lib/pcre2.ecmp
  extra/src/lib/spirv-headers.ecmp
  extra/src/lib/spirv-llvm-translator.ecmp
  extra/src/lib/spirv-tools.ecmp
  extra/src/utils/Mako.ecmp
  extra/src/utils/cbindgen.ecmp
  extra/src/utils/desktop-file-utils.ecmp
  extra/src/utils/docutils.ecmp
  extra/src/utils/hwdata.ecmp
  extra/src/utils/llvm.ecmp
  extra/src/utils/packaging.ecmp
  extra/src/utils/ply.ecmp
  extra/src/utils/rust-bindgen.ecmp
  extra/src/utils/shared-mime-info.ecmp
  extra/src/wayland-protocols.ecmp
  extra/src/wayland.ecmp
  extra/src/weston.ecmp
Labels: size/XXL

#151 Update: libspm to cf9d28066358f1ddeaa203a4b1ad3551dac85e26
  base/src/libspm.ecmp
  base/src/neofetch.ecmp
  base/src/pcre2.ecmp
  extra/src/lib/pcre2.ecmp
  extra/src/neofetch.ecmp
Labels: size/M

#153 Fixed: incorrect prefix in libgit2
  base/src/libgit2.ecmp
  extra/src/graphics/seatd.ecmp
Labels: size/S

#152 Add tmux and libevent
  extra/src/lib/libevent.ecmp
  extra/src/tmux.ecmp
Labels: size/M
